/*
 * This file is generated by jOOQ.
*/
package stroom.db.auth.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.db.auth.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record11<Integer, String, Byte, Timestamp, Timestamp, String, Integer, Timestamp, String, Timestamp, String> {

    private static final long serialVersionUID = -238350785;

    /**
     * Setter for <code>auth.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>auth.users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>auth.users.is_login_expired</code>.
     */
    public void setIsLoginExpired(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.users.is_login_expired</code>.
     */
    public Byte getIsLoginExpired() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>auth.users.last_login</code>.
     */
    public void setLastLogin(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.users.last_login</code>.
     */
    public Timestamp getLastLogin() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>auth.users.password_expiration</code>.
     */
    public void setPasswordExpiration(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.users.password_expiration</code>.
     */
    public Timestamp getPasswordExpiration() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>auth.users.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(5);
    }

    /**
     * Setter for <code>auth.users.total_login_failures</code>.
     */
    public void setTotalLoginFailures(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.users.total_login_failures</code>.
     */
    public Integer getTotalLoginFailures() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>auth.users.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>auth.users.created_by_user</code>.
     */
    public void setCreatedByUser(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.users.created_by_user</code>.
     */
    public String getCreatedByUser() {
        return (String) get(8);
    }

    /**
     * Setter for <code>auth.users.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.users.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>auth.users.updated_by_user</code>.
     */
    public void setUpdatedByUser(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.users.updated_by_user</code>.
     */
    public String getUpdatedByUser() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Byte, Timestamp, Timestamp, String, Integer, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Byte, Timestamp, Timestamp, String, Integer, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Users.USERS.IS_LOGIN_EXPIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Users.USERS.LAST_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Users.USERS.PASSWORD_EXPIRATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Users.USERS.PASSWORD_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Users.USERS.TOTAL_LOGIN_FAILURES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Users.USERS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users.USERS.CREATED_BY_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Users.USERS.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Users.USERS.UPDATED_BY_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getIsLoginExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getPasswordExpiration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPasswordHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTotalLoginFailures();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreatedByUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUpdatedByUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(Byte value) {
        setIsLoginExpired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Timestamp value) {
        setLastLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(Timestamp value) {
        setPasswordExpiration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(String value) {
        setPasswordHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(Integer value) {
        setTotalLoginFailures(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(String value) {
        setCreatedByUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(String value) {
        setUpdatedByUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(Integer value1, String value2, Byte value3, Timestamp value4, Timestamp value5, String value6, Integer value7, Timestamp value8, String value9, Timestamp value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, Byte isLoginExpired, Timestamp lastLogin, Timestamp passwordExpiration, String passwordHash, Integer totalLoginFailures, Timestamp createdOn, String createdByUser, Timestamp updatedOn, String updatedByUser) {
        super(Users.USERS);

        set(0, id);
        set(1, name);
        set(2, isLoginExpired);
        set(3, lastLogin);
        set(4, passwordExpiration);
        set(5, passwordHash);
        set(6, totalLoginFailures);
        set(7, createdOn);
        set(8, createdByUser);
        set(9, updatedOn);
        set(10, updatedByUser);
    }
}
