language: java
dist: trusty
group: edge
jdk: openjdk8
sudo: required # To ensure we get a VM rather than a container for more memory and for all the apt-get stuff

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken>`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: "MMzx2PxzjMuJL7S74SxL3ZWdGiOqBh/geLJJIftY9ReswLVvJbxurB0PDYvdPw8E/bJ7ykWjR99mLBi2K7FV+SavBTVXEwvw8T8AO9TQe7x5RkIQu+jeM2wf8KfABPUDrdA7PlbA8cVO9LAUTBMTJ6E7x4+3khpqjmBZGxRzTAECDyHKeHIioDfRFkZsnn5JzcoiUk1TLk8snubIL7mE0euVylSdYUPHUO7OWe7DNzoOuWcXOQmIwuhTIDeKSv5aGLuLVbILvvngzFhpdr28dsapAgvJZMBC6dfGJbb59/RH3M7rE+WIOVjb1+npDxWsuhE8rAYJZIb5id0BqxjVyPJl05g+zIe8FICrNgRlTYqgF4uxrR02AvEAf0mDAHd+KralBA9sz8Q/IBmw7sfkq+8jYslLOa1GA/DDXjWJ/KGZPmIxj3HaMjjepyOjO2LIZIItQ2XsoUPDxra5BAUU5c7InKJpEiFw9dlhfjlJBJE1QBowUgVmlrrYBSI92mB8dQlYyyPBUP2pz5RoqnpBjyLg5vccAzWFiI76fRXmCXuZz51GmT+e2p6ZFD5rQ+KiTqpWIdz8vQ1jt+nRS9ufDzNgYeR0cykNmYnaJJETdi+LcZQefZcRN+X/bJqy4vLsYxxDSMo2IwsUgr/knSwdt4ZdKK2cDla0HyeKnwFAzOs="
    - RESOURCES_BRANCH: master
    - STROOM_TAG: v6-LATEST

before_install:
  - docker --version
  - docker-compose --version

before_script: ./travis.before_script.sh

install: echo "skip 'gradle assemble' step to speed up build"

script: ./travis.script.sh

## Push to GitHub releases for any tagged commit - the key was generated by the Travis CLI: `$ travis setup releases`
deploy:
  provider: releases
  api_key:
      # travis encrypt -r gchq/stroom-auth <github personal access token>
    secure: jf4TLfIGFf3O3S/6AMcK1LM/yT3W4AjvunqWICcbXwNiQjGOp/3fig1y5rdtRrjHFQ0fYPUUqzCstCRavBOoO+0pjwoqL1Xi+9wAgrD4uvdp9pPJ47txsVOLfUfyk8za2Za0lLipqr70wUI47903EtbDHrTPlHjFh9HMDUb4UxYdx1IXUE0uDqgVETWZ0Wi/sCjBJ53mYowth5gnp/7YTKxRdn48jyAmF4OsditiIpD/4kmCgPEsUO0otsU7KRoyW3NiyiWTRFDs3nv9WbBnfDF1eB8ewmrN3jek2XLd8p0qjpgNt+3H+Vk/FSkAiuumReLsaaHZ4AsS7jomtGkeAaYdR4FoSQ8ScXMA6gyhyr/3QAF1oQkO8taUjwjMDs945gZcErVAyLHTo4W+oc2iHMqQfeQTlPprb/a5ZzwNTZs2KidIf0rWdpNrik/BrI1chjvyqPqXOnk7M9EDvFIxxs0M+yE9DoNHWCj9VPADdLPt3W5oPeKp+ZZTiCwhHqrRNI7MKxngpOqVoUoalVF27ohNluAZHFCE1a1hLC11+ipazi7aPlV6GrYzXW1GxWOtDBHF1N9/eEDoYEdzc+oZAEy2oGOjZpC2EQepD5tlqrsT6dWR/obn7J+7i7oV8ELdbExSq7R1Guy1YpI8IBGswQaTPteYdq83HGvrypaf5/k=
  file: 
    - stroom-persistence/src/scripts/transform_user_extract.py
  skip_cleanup: true
  on:
    repo: gchq/stroom-auth
    tags: true

# Clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - libs
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

