/*
 * This file is generated by jOOQ.
*/
package stroom.db.auth.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.db.auth.Auth;
import stroom.db.auth.Keys;
import stroom.db.auth.tables.records.TokenTypesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenTypes extends TableImpl<TokenTypesRecord> {

    private static final long serialVersionUID = 1939786109;

    /**
     * The reference instance of <code>auth.token_types</code>
     */
    public static final TokenTypes TOKEN_TYPES = new TokenTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TokenTypesRecord> getRecordType() {
        return TokenTypesRecord.class;
    }

    /**
     * The column <code>auth.token_types.id</code>.
     */
    public final TableField<TokenTypesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>auth.token_types.token_type</code>.
     */
    public final TableField<TokenTypesRecord, String> TOKEN_TYPE = createField("token_type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>auth.token_types</code> table reference
     */
    public TokenTypes() {
        this("token_types", null);
    }

    /**
     * Create an aliased <code>auth.token_types</code> table reference
     */
    public TokenTypes(String alias) {
        this(alias, TOKEN_TYPES);
    }

    private TokenTypes(String alias, Table<TokenTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TokenTypes(String alias, Table<TokenTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Auth.AUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TokenTypesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TOKEN_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TokenTypesRecord> getPrimaryKey() {
        return Keys.KEY_TOKEN_TYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TokenTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<TokenTypesRecord>>asList(Keys.KEY_TOKEN_TYPES_PRIMARY, Keys.KEY_TOKEN_TYPES_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenTypes as(String alias) {
        return new TokenTypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TokenTypes rename(String name) {
        return new TokenTypes(name, null);
    }
}
