/*
 * This file is generated by jOOQ.
*/
package stroom.db.auth;


import javax.annotation.Generated;

import stroom.db.auth.tables.Users;


/**
 * Convenience access to all tables in auth
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>auth.users</code>.
     */
    public static final Users USERS = stroom.db.auth.tables.Users.USERS;
}
