/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models;


import javax.annotation.Generated;

import stroom.models.tables.AnalOutDatSrc;
import stroom.models.tables.AppPerm;
import stroom.models.tables.ClstrLk;
import stroom.models.tables.Dash;
import stroom.models.tables.Dict;
import stroom.models.tables.DocPerm;
import stroom.models.tables.Fd;
import stroom.models.tables.Folder;
import stroom.models.tables.GlobProp;
import stroom.models.tables.Idx;
import stroom.models.tables.IdxShrd;
import stroom.models.tables.IdxVol;
import stroom.models.tables.Jb;
import stroom.models.tables.JbNd;
import stroom.models.tables.Nd;
import stroom.models.tables.Perm;
import stroom.models.tables.Pipe;
import stroom.models.tables.Query;
import stroom.models.tables.Res;
import stroom.models.tables.Rk;
import stroom.models.tables.SchemaVersion;
import stroom.models.tables.Script;
import stroom.models.tables.SqlStatKey;
import stroom.models.tables.SqlStatVal;
import stroom.models.tables.SqlStatValSrc;
import stroom.models.tables.StatDatSrc;
import stroom.models.tables.StateDatSrc;
import stroom.models.tables.Strm;
import stroom.models.tables.StrmAtrKey;
import stroom.models.tables.StrmAtrVal;
import stroom.models.tables.StrmProc;
import stroom.models.tables.StrmProcFilt;
import stroom.models.tables.StrmProcFiltTrac;
import stroom.models.tables.StrmTask;
import stroom.models.tables.StrmTp;
import stroom.models.tables.StrmVol;
import stroom.models.tables.StroomStatsStore;
import stroom.models.tables.TempStrmAttributeId;
import stroom.models.tables.TempStrmId;
import stroom.models.tables.TxtConv;
import stroom.models.tables.Usr;
import stroom.models.tables.UsrGrpUsr;
import stroom.models.tables.Vis;
import stroom.models.tables.Vol;
import stroom.models.tables.VolState;
import stroom.models.tables.XmlSchema;
import stroom.models.tables.Xslt;


/**
 * Convenience access to all tables in stroom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.ANAL_OUT_DAT_SRC</code>.
     */
    public static final AnalOutDatSrc ANAL_OUT_DAT_SRC = stroom.models.tables.AnalOutDatSrc.ANAL_OUT_DAT_SRC;

    /**
     * The table <code>stroom.APP_PERM</code>.
     */
    public static final AppPerm APP_PERM = stroom.models.tables.AppPerm.APP_PERM;

    /**
     * The table <code>stroom.CLSTR_LK</code>.
     */
    public static final ClstrLk CLSTR_LK = stroom.models.tables.ClstrLk.CLSTR_LK;

    /**
     * The table <code>stroom.DASH</code>.
     */
    public static final Dash DASH = stroom.models.tables.Dash.DASH;

    /**
     * The table <code>stroom.DICT</code>.
     */
    public static final Dict DICT = stroom.models.tables.Dict.DICT;

    /**
     * The table <code>stroom.DOC_PERM</code>.
     */
    public static final DocPerm DOC_PERM = stroom.models.tables.DocPerm.DOC_PERM;

    /**
     * The table <code>stroom.FD</code>.
     */
    public static final Fd FD = stroom.models.tables.Fd.FD;

    /**
     * The table <code>stroom.FOLDER</code>.
     */
    public static final Folder FOLDER = stroom.models.tables.Folder.FOLDER;

    /**
     * The table <code>stroom.GLOB_PROP</code>.
     */
    public static final GlobProp GLOB_PROP = stroom.models.tables.GlobProp.GLOB_PROP;

    /**
     * The table <code>stroom.IDX</code>.
     */
    public static final Idx IDX = stroom.models.tables.Idx.IDX;

    /**
     * The table <code>stroom.IDX_SHRD</code>.
     */
    public static final IdxShrd IDX_SHRD = stroom.models.tables.IdxShrd.IDX_SHRD;

    /**
     * The table <code>stroom.IDX_VOL</code>.
     */
    public static final IdxVol IDX_VOL = stroom.models.tables.IdxVol.IDX_VOL;

    /**
     * The table <code>stroom.JB</code>.
     */
    public static final Jb JB = stroom.models.tables.Jb.JB;

    /**
     * The table <code>stroom.JB_ND</code>.
     */
    public static final JbNd JB_ND = stroom.models.tables.JbNd.JB_ND;

    /**
     * The table <code>stroom.ND</code>.
     */
    public static final Nd ND = stroom.models.tables.Nd.ND;

    /**
     * The table <code>stroom.PERM</code>.
     */
    public static final Perm PERM = stroom.models.tables.Perm.PERM;

    /**
     * The table <code>stroom.PIPE</code>.
     */
    public static final Pipe PIPE = stroom.models.tables.Pipe.PIPE;

    /**
     * The table <code>stroom.QUERY</code>.
     */
    public static final Query QUERY = stroom.models.tables.Query.QUERY;

    /**
     * The table <code>stroom.RES</code>.
     */
    public static final Res RES = stroom.models.tables.Res.RES;

    /**
     * The table <code>stroom.RK</code>.
     */
    public static final Rk RK = stroom.models.tables.Rk.RK;

    /**
     * The table <code>stroom.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = stroom.models.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>stroom.SCRIPT</code>.
     */
    public static final Script SCRIPT = stroom.models.tables.Script.SCRIPT;

    /**
     * The table <code>stroom.SQL_STAT_KEY</code>.
     */
    public static final SqlStatKey SQL_STAT_KEY = stroom.models.tables.SqlStatKey.SQL_STAT_KEY;

    /**
     * The table <code>stroom.SQL_STAT_VAL</code>.
     */
    public static final SqlStatVal SQL_STAT_VAL = stroom.models.tables.SqlStatVal.SQL_STAT_VAL;

    /**
     * The table <code>stroom.SQL_STAT_VAL_SRC</code>.
     */
    public static final SqlStatValSrc SQL_STAT_VAL_SRC = stroom.models.tables.SqlStatValSrc.SQL_STAT_VAL_SRC;

    /**
     * The table <code>stroom.STATE_DAT_SRC</code>.
     */
    public static final StateDatSrc STATE_DAT_SRC = stroom.models.tables.StateDatSrc.STATE_DAT_SRC;

    /**
     * The table <code>stroom.STAT_DAT_SRC</code>.
     */
    public static final StatDatSrc STAT_DAT_SRC = stroom.models.tables.StatDatSrc.STAT_DAT_SRC;

    /**
     * The table <code>stroom.STRM</code>.
     */
    public static final Strm STRM = stroom.models.tables.Strm.STRM;

    /**
     * The table <code>stroom.STRM_ATR_KEY</code>.
     */
    public static final StrmAtrKey STRM_ATR_KEY = stroom.models.tables.StrmAtrKey.STRM_ATR_KEY;

    /**
     * The table <code>stroom.STRM_ATR_VAL</code>.
     */
    public static final StrmAtrVal STRM_ATR_VAL = stroom.models.tables.StrmAtrVal.STRM_ATR_VAL;

    /**
     * The table <code>stroom.STRM_PROC</code>.
     */
    public static final StrmProc STRM_PROC = stroom.models.tables.StrmProc.STRM_PROC;

    /**
     * The table <code>stroom.STRM_PROC_FILT</code>.
     */
    public static final StrmProcFilt STRM_PROC_FILT = stroom.models.tables.StrmProcFilt.STRM_PROC_FILT;

    /**
     * The table <code>stroom.STRM_PROC_FILT_TRAC</code>.
     */
    public static final StrmProcFiltTrac STRM_PROC_FILT_TRAC = stroom.models.tables.StrmProcFiltTrac.STRM_PROC_FILT_TRAC;

    /**
     * The table <code>stroom.STRM_TASK</code>.
     */
    public static final StrmTask STRM_TASK = stroom.models.tables.StrmTask.STRM_TASK;

    /**
     * The table <code>stroom.STRM_TP</code>.
     */
    public static final StrmTp STRM_TP = stroom.models.tables.StrmTp.STRM_TP;

    /**
     * The table <code>stroom.STRM_VOL</code>.
     */
    public static final StrmVol STRM_VOL = stroom.models.tables.StrmVol.STRM_VOL;

    /**
     * The table <code>stroom.STROOM_STATS_STORE</code>.
     */
    public static final StroomStatsStore STROOM_STATS_STORE = stroom.models.tables.StroomStatsStore.STROOM_STATS_STORE;

    /**
     * The table <code>stroom.TEMP_STRM_ATTRIBUTE_ID</code>.
     */
    public static final TempStrmAttributeId TEMP_STRM_ATTRIBUTE_ID = stroom.models.tables.TempStrmAttributeId.TEMP_STRM_ATTRIBUTE_ID;

    /**
     * The table <code>stroom.TEMP_STRM_ID</code>.
     */
    public static final TempStrmId TEMP_STRM_ID = stroom.models.tables.TempStrmId.TEMP_STRM_ID;

    /**
     * The table <code>stroom.TXT_CONV</code>.
     */
    public static final TxtConv TXT_CONV = stroom.models.tables.TxtConv.TXT_CONV;

    /**
     * The table <code>stroom.USR</code>.
     */
    public static final Usr USR = stroom.models.tables.Usr.USR;

    /**
     * The table <code>stroom.USR_GRP_USR</code>.
     */
    public static final UsrGrpUsr USR_GRP_USR = stroom.models.tables.UsrGrpUsr.USR_GRP_USR;

    /**
     * The table <code>stroom.VIS</code>.
     */
    public static final Vis VIS = stroom.models.tables.Vis.VIS;

    /**
     * The table <code>stroom.VOL</code>.
     */
    public static final Vol VOL = stroom.models.tables.Vol.VOL;

    /**
     * The table <code>stroom.VOL_STATE</code>.
     */
    public static final VolState VOL_STATE = stroom.models.tables.VolState.VOL_STATE;

    /**
     * The table <code>stroom.XML_SCHEMA</code>.
     */
    public static final XmlSchema XML_SCHEMA = stroom.models.tables.XmlSchema.XML_SCHEMA;

    /**
     * The table <code>stroom.XSLT</code>.
     */
    public static final Xslt XSLT = stroom.models.tables.Xslt.XSLT;
}
