/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.AppPermRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppPerm extends TableImpl<AppPermRecord> {

    private static final long serialVersionUID = -755257840;

    /**
     * The reference instance of <code>stroom.APP_PERM</code>
     */
    public static final AppPerm APP_PERM = new AppPerm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppPermRecord> getRecordType() {
        return AppPermRecord.class;
    }

    /**
     * The column <code>stroom.APP_PERM.ID</code>.
     */
    public final TableField<AppPermRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.APP_PERM.VER</code>.
     */
    public final TableField<AppPermRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.APP_PERM.USR_UUID</code>.
     */
    public final TableField<AppPermRecord, String> USR_UUID = createField("USR_UUID", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.APP_PERM.FK_PERM_ID</code>.
     */
    public final TableField<AppPermRecord, Integer> FK_PERM_ID = createField("FK_PERM_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>stroom.APP_PERM</code> table reference
     */
    public AppPerm() {
        this("APP_PERM", null);
    }

    /**
     * Create an aliased <code>stroom.APP_PERM</code> table reference
     */
    public AppPerm(String alias) {
        this(alias, APP_PERM);
    }

    private AppPerm(String alias, Table<AppPermRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppPerm(String alias, Table<AppPermRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AppPermRecord, Long> getIdentity() {
        return Keys.IDENTITY_APP_PERM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppPermRecord> getPrimaryKey() {
        return Keys.KEY_APP_PERM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppPermRecord>> getKeys() {
        return Arrays.<UniqueKey<AppPermRecord>>asList(Keys.KEY_APP_PERM_PRIMARY, Keys.KEY_APP_PERM_APP_PERM_USR_UUID_FK_PERM_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppPerm as(String alias) {
        return new AppPerm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppPerm rename(String name) {
        return new AppPerm(name, null);
    }
}
