/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.JbRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jb extends TableImpl<JbRecord> {

    private static final long serialVersionUID = -1779591602;

    /**
     * The reference instance of <code>stroom.JB</code>
     */
    public static final Jb JB = new Jb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JbRecord> getRecordType() {
        return JbRecord.class;
    }

    /**
     * The column <code>stroom.JB.ID</code>.
     */
    public final TableField<JbRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.JB.VER</code>.
     */
    public final TableField<JbRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.JB.CRT_USER</code>.
     */
    public final TableField<JbRecord, String> CRT_USER = createField("CRT_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.JB.UPD_USER</code>.
     */
    public final TableField<JbRecord, String> UPD_USER = createField("UPD_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.JB.NAME</code>.
     */
    public final TableField<JbRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.JB.ENBL</code>.
     */
    public final TableField<JbRecord, Boolean> ENBL = createField("ENBL", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>stroom.JB.CRT_MS</code>.
     */
    public final TableField<JbRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.JB.UPD_MS</code>.
     */
    public final TableField<JbRecord, Long> UPD_MS = createField("UPD_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>stroom.JB</code> table reference
     */
    public Jb() {
        this("JB", null);
    }

    /**
     * Create an aliased <code>stroom.JB</code> table reference
     */
    public Jb(String alias) {
        this(alias, JB);
    }

    private Jb(String alias, Table<JbRecord> aliased) {
        this(alias, aliased, null);
    }

    private Jb(String alias, Table<JbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JbRecord, Integer> getIdentity() {
        return Keys.IDENTITY_JB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JbRecord> getPrimaryKey() {
        return Keys.KEY_JB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JbRecord>> getKeys() {
        return Arrays.<UniqueKey<JbRecord>>asList(Keys.KEY_JB_PRIMARY, Keys.KEY_JB_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Jb as(String alias) {
        return new Jb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Jb rename(String name) {
        return new Jb(name, null);
    }
}
