/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.JbNdRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JbNd extends TableImpl<JbNdRecord> {

    private static final long serialVersionUID = -1640212106;

    /**
     * The reference instance of <code>stroom.JB_ND</code>
     */
    public static final JbNd JB_ND = new JbNd();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JbNdRecord> getRecordType() {
        return JbNdRecord.class;
    }

    /**
     * The column <code>stroom.JB_ND.ID</code>.
     */
    public final TableField<JbNdRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.VER</code>.
     */
    public final TableField<JbNdRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.CRT_USER</code>.
     */
    public final TableField<JbNdRecord, String> CRT_USER = createField("CRT_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.JB_ND.UPD_USER</code>.
     */
    public final TableField<JbNdRecord, String> UPD_USER = createField("UPD_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.JB_ND.JB_TP</code>.
     */
    public final TableField<JbNdRecord, Byte> JB_TP = createField("JB_TP", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.ENBL</code>.
     */
    public final TableField<JbNdRecord, Boolean> ENBL = createField("ENBL", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.SCHEDULE</code>.
     */
    public final TableField<JbNdRecord, String> SCHEDULE = createField("SCHEDULE", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.JB_ND.TASK_LMT</code>.
     */
    public final TableField<JbNdRecord, Integer> TASK_LMT = createField("TASK_LMT", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.FK_JB_ID</code>.
     */
    public final TableField<JbNdRecord, Integer> FK_JB_ID = createField("FK_JB_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.FK_ND_ID</code>.
     */
    public final TableField<JbNdRecord, Integer> FK_ND_ID = createField("FK_ND_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.JB_ND.CRT_MS</code>.
     */
    public final TableField<JbNdRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.JB_ND.UPD_MS</code>.
     */
    public final TableField<JbNdRecord, Long> UPD_MS = createField("UPD_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>stroom.JB_ND</code> table reference
     */
    public JbNd() {
        this("JB_ND", null);
    }

    /**
     * Create an aliased <code>stroom.JB_ND</code> table reference
     */
    public JbNd(String alias) {
        this(alias, JB_ND);
    }

    private JbNd(String alias, Table<JbNdRecord> aliased) {
        this(alias, aliased, null);
    }

    private JbNd(String alias, Table<JbNdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JbNdRecord, Integer> getIdentity() {
        return Keys.IDENTITY_JB_ND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JbNdRecord> getPrimaryKey() {
        return Keys.KEY_JB_ND_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JbNdRecord>> getKeys() {
        return Arrays.<UniqueKey<JbNdRecord>>asList(Keys.KEY_JB_ND_PRIMARY, Keys.KEY_JB_ND_FK_ND_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<JbNdRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<JbNdRecord, ?>>asList(Keys.JB_ND_FK_JB_ID, Keys.JB_ND_FK_ND_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JbNd as(String alias) {
        return new JbNd(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JbNd rename(String name) {
        return new JbNd(name, null);
    }
}
