/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.PermRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Perm extends TableImpl<PermRecord> {

    private static final long serialVersionUID = -170681297;

    /**
     * The reference instance of <code>stroom.PERM</code>
     */
    public static final Perm PERM = new Perm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermRecord> getRecordType() {
        return PermRecord.class;
    }

    /**
     * The column <code>stroom.PERM.ID</code>.
     */
    public final TableField<PermRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.PERM.VER</code>.
     */
    public final TableField<PermRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.PERM.NAME</code>.
     */
    public final TableField<PermRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>stroom.PERM</code> table reference
     */
    public Perm() {
        this("PERM", null);
    }

    /**
     * Create an aliased <code>stroom.PERM</code> table reference
     */
    public Perm(String alias) {
        this(alias, PERM);
    }

    private Perm(String alias, Table<PermRecord> aliased) {
        this(alias, aliased, null);
    }

    private Perm(String alias, Table<PermRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PermRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PERM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PermRecord> getPrimaryKey() {
        return Keys.KEY_PERM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PermRecord>> getKeys() {
        return Arrays.<UniqueKey<PermRecord>>asList(Keys.KEY_PERM_PRIMARY, Keys.KEY_PERM_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Perm as(String alias) {
        return new Perm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Perm rename(String name) {
        return new Perm(name, null);
    }
}
