/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.PipeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pipe extends TableImpl<PipeRecord> {

    private static final long serialVersionUID = 1480299504;

    /**
     * The reference instance of <code>stroom.PIPE</code>
     */
    public static final Pipe PIPE = new Pipe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PipeRecord> getRecordType() {
        return PipeRecord.class;
    }

    /**
     * The column <code>stroom.PIPE.ID</code>.
     */
    public final TableField<PipeRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.PIPE.VER</code>.
     */
    public final TableField<PipeRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.PIPE.CRT_MS</code>.
     */
    public final TableField<PipeRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.PIPE.CRT_USER</code>.
     */
    public final TableField<PipeRecord, String> CRT_USER = createField("CRT_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.PIPE.UPD_MS</code>.
     */
    public final TableField<PipeRecord, Long> UPD_MS = createField("UPD_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.PIPE.UPD_USER</code>.
     */
    public final TableField<PipeRecord, String> UPD_USER = createField("UPD_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.PIPE.NAME</code>.
     */
    public final TableField<PipeRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.PIPE.UUID</code>.
     */
    public final TableField<PipeRecord, String> UUID = createField("UUID", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.PIPE.DESCRIP</code>.
     */
    public final TableField<PipeRecord, String> DESCRIP = createField("DESCRIP", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.PIPE.PARNT_PIPE</code>.
     */
    public final TableField<PipeRecord, String> PARNT_PIPE = createField("PARNT_PIPE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.PIPE.DAT</code>.
     */
    public final TableField<PipeRecord, String> DAT = createField("DAT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.PIPE.PIPE_TP</code>.
     */
    public final TableField<PipeRecord, String> PIPE_TP = createField("PIPE_TP", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.PIPE.FK_FOLDER_ID</code>.
     */
    public final TableField<PipeRecord, Integer> FK_FOLDER_ID = createField("FK_FOLDER_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>stroom.PIPE</code> table reference
     */
    public Pipe() {
        this("PIPE", null);
    }

    /**
     * Create an aliased <code>stroom.PIPE</code> table reference
     */
    public Pipe(String alias) {
        this(alias, PIPE);
    }

    private Pipe(String alias, Table<PipeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Pipe(String alias, Table<PipeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PipeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PIPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PipeRecord> getPrimaryKey() {
        return Keys.KEY_PIPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PipeRecord>> getKeys() {
        return Arrays.<UniqueKey<PipeRecord>>asList(Keys.KEY_PIPE_PRIMARY, Keys.KEY_PIPE_NAME, Keys.KEY_PIPE_UUID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PipeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PipeRecord, ?>>asList(Keys.PIPE_FK_FOLDER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Pipe as(String alias) {
        return new Pipe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pipe rename(String name) {
        return new Pipe(name, null);
    }
}
