/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.SqlStatKeyRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqlStatKey extends TableImpl<SqlStatKeyRecord> {

    private static final long serialVersionUID = -1680836836;

    /**
     * The reference instance of <code>stroom.SQL_STAT_KEY</code>
     */
    public static final SqlStatKey SQL_STAT_KEY = new SqlStatKey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SqlStatKeyRecord> getRecordType() {
        return SqlStatKeyRecord.class;
    }

    /**
     * The column <code>stroom.SQL_STAT_KEY.ID</code>.
     */
    public final TableField<SqlStatKeyRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_KEY.VER</code>.
     */
    public final TableField<SqlStatKeyRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_KEY.NAME</code>.
     */
    public final TableField<SqlStatKeyRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(766).nullable(false), this, "");

    /**
     * Create a <code>stroom.SQL_STAT_KEY</code> table reference
     */
    public SqlStatKey() {
        this("SQL_STAT_KEY", null);
    }

    /**
     * Create an aliased <code>stroom.SQL_STAT_KEY</code> table reference
     */
    public SqlStatKey(String alias) {
        this(alias, SQL_STAT_KEY);
    }

    private SqlStatKey(String alias, Table<SqlStatKeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private SqlStatKey(String alias, Table<SqlStatKeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SqlStatKeyRecord, Long> getIdentity() {
        return Keys.IDENTITY_SQL_STAT_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SqlStatKeyRecord> getPrimaryKey() {
        return Keys.KEY_SQL_STAT_KEY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SqlStatKeyRecord>> getKeys() {
        return Arrays.<UniqueKey<SqlStatKeyRecord>>asList(Keys.KEY_SQL_STAT_KEY_PRIMARY, Keys.KEY_SQL_STAT_KEY_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SqlStatKey as(String alias) {
        return new SqlStatKey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SqlStatKey rename(String name) {
        return new SqlStatKey(name, null);
    }
}
