/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.SqlStatValRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqlStatVal extends TableImpl<SqlStatValRecord> {

    private static final long serialVersionUID = -1182692122;

    /**
     * The reference instance of <code>stroom.SQL_STAT_VAL</code>
     */
    public static final SqlStatVal SQL_STAT_VAL = new SqlStatVal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SqlStatValRecord> getRecordType() {
        return SqlStatValRecord.class;
    }

    /**
     * The column <code>stroom.SQL_STAT_VAL.TIME_MS</code>.
     */
    public final TableField<SqlStatValRecord, Long> TIME_MS = createField("TIME_MS", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_VAL.PRES</code>.
     */
    public final TableField<SqlStatValRecord, Byte> PRES = createField("PRES", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_VAL.VAL_TP</code>.
     */
    public final TableField<SqlStatValRecord, Byte> VAL_TP = createField("VAL_TP", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_VAL.VAL</code>.
     */
    public final TableField<SqlStatValRecord, Long> VAL = createField("VAL", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_VAL.CT</code>.
     */
    public final TableField<SqlStatValRecord, Long> CT = createField("CT", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.SQL_STAT_VAL.FK_SQL_STAT_KEY_ID</code>.
     */
    public final TableField<SqlStatValRecord, Long> FK_SQL_STAT_KEY_ID = createField("FK_SQL_STAT_KEY_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>stroom.SQL_STAT_VAL</code> table reference
     */
    public SqlStatVal() {
        this("SQL_STAT_VAL", null);
    }

    /**
     * Create an aliased <code>stroom.SQL_STAT_VAL</code> table reference
     */
    public SqlStatVal(String alias) {
        this(alias, SQL_STAT_VAL);
    }

    private SqlStatVal(String alias, Table<SqlStatValRecord> aliased) {
        this(alias, aliased, null);
    }

    private SqlStatVal(String alias, Table<SqlStatValRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SqlStatValRecord> getPrimaryKey() {
        return Keys.KEY_SQL_STAT_VAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SqlStatValRecord>> getKeys() {
        return Arrays.<UniqueKey<SqlStatValRecord>>asList(Keys.KEY_SQL_STAT_VAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SqlStatValRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SqlStatValRecord, ?>>asList(Keys.SQL_STAT_VAL_FK_STAT_KEY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SqlStatVal as(String alias) {
        return new SqlStatVal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SqlStatVal rename(String name) {
        return new SqlStatVal(name, null);
    }
}
