/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.StrmVolRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmVol extends TableImpl<StrmVolRecord> {

    private static final long serialVersionUID = 558999126;

    /**
     * The reference instance of <code>stroom.STRM_VOL</code>
     */
    public static final StrmVol STRM_VOL = new StrmVol();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StrmVolRecord> getRecordType() {
        return StrmVolRecord.class;
    }

    /**
     * The column <code>stroom.STRM_VOL.ID</code>.
     */
    public final TableField<StrmVolRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_VOL.VER</code>.
     */
    public final TableField<StrmVolRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_VOL.FK_STRM_ID</code>.
     */
    public final TableField<StrmVolRecord, Long> FK_STRM_ID = createField("FK_STRM_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_VOL.FK_VOL_ID</code>.
     */
    public final TableField<StrmVolRecord, Integer> FK_VOL_ID = createField("FK_VOL_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>stroom.STRM_VOL</code> table reference
     */
    public StrmVol() {
        this("STRM_VOL", null);
    }

    /**
     * Create an aliased <code>stroom.STRM_VOL</code> table reference
     */
    public StrmVol(String alias) {
        this(alias, STRM_VOL);
    }

    private StrmVol(String alias, Table<StrmVolRecord> aliased) {
        this(alias, aliased, null);
    }

    private StrmVol(String alias, Table<StrmVolRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StrmVolRecord, Long> getIdentity() {
        return Keys.IDENTITY_STRM_VOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StrmVolRecord> getPrimaryKey() {
        return Keys.KEY_STRM_VOL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StrmVolRecord>> getKeys() {
        return Arrays.<UniqueKey<StrmVolRecord>>asList(Keys.KEY_STRM_VOL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StrmVolRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StrmVolRecord, ?>>asList(Keys.STRM_VOL_FK_STRM_ID, Keys.STRM_VOL_FK_VOL_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmVol as(String alias) {
        return new StrmVol(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StrmVol rename(String name) {
        return new StrmVol(name, null);
    }
}
