/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.StrmProcFiltRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmProcFilt extends TableImpl<StrmProcFiltRecord> {

    private static final long serialVersionUID = 118098284;

    /**
     * The reference instance of <code>stroom.STRM_PROC_FILT</code>
     */
    public static final StrmProcFilt STRM_PROC_FILT = new StrmProcFilt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StrmProcFiltRecord> getRecordType() {
        return StrmProcFiltRecord.class;
    }

    /**
     * The column <code>stroom.STRM_PROC_FILT.ID</code>.
     */
    public final TableField<StrmProcFiltRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.VER</code>.
     */
    public final TableField<StrmProcFiltRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.CRT_MS</code>.
     */
    public final TableField<StrmProcFiltRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.CRT_USER</code>.
     */
    public final TableField<StrmProcFiltRecord, String> CRT_USER = createField("CRT_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.UPD_MS</code>.
     */
    public final TableField<StrmProcFiltRecord, Long> UPD_MS = createField("UPD_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.UPD_USER</code>.
     */
    public final TableField<StrmProcFiltRecord, String> UPD_USER = createField("UPD_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.DAT</code>.
     */
    public final TableField<StrmProcFiltRecord, String> DAT = createField("DAT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.PRIOR</code>.
     */
    public final TableField<StrmProcFiltRecord, Integer> PRIOR = createField("PRIOR", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.FK_STRM_PROC_ID</code>.
     */
    public final TableField<StrmProcFiltRecord, Integer> FK_STRM_PROC_ID = createField("FK_STRM_PROC_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.FK_STRM_PROC_FILT_TRAC_ID</code>.
     */
    public final TableField<StrmProcFiltRecord, Integer> FK_STRM_PROC_FILT_TRAC_ID = createField("FK_STRM_PROC_FILT_TRAC_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_PROC_FILT.ENBL</code>.
     */
    public final TableField<StrmProcFiltRecord, Boolean> ENBL = createField("ENBL", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * Create a <code>stroom.STRM_PROC_FILT</code> table reference
     */
    public StrmProcFilt() {
        this("STRM_PROC_FILT", null);
    }

    /**
     * Create an aliased <code>stroom.STRM_PROC_FILT</code> table reference
     */
    public StrmProcFilt(String alias) {
        this(alias, STRM_PROC_FILT);
    }

    private StrmProcFilt(String alias, Table<StrmProcFiltRecord> aliased) {
        this(alias, aliased, null);
    }

    private StrmProcFilt(String alias, Table<StrmProcFiltRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StrmProcFiltRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STRM_PROC_FILT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StrmProcFiltRecord> getPrimaryKey() {
        return Keys.KEY_STRM_PROC_FILT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StrmProcFiltRecord>> getKeys() {
        return Arrays.<UniqueKey<StrmProcFiltRecord>>asList(Keys.KEY_STRM_PROC_FILT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StrmProcFiltRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StrmProcFiltRecord, ?>>asList(Keys.STRM_PROC_FILT_FK_STRM_PROC_ID, Keys.STRM_PROC_FILT_FK_STRM_PROC_FILT_TRAC_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFilt as(String alias) {
        return new StrmProcFilt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StrmProcFilt rename(String name) {
        return new StrmProcFilt(name, null);
    }
}
