/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.StrmTaskRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmTask extends TableImpl<StrmTaskRecord> {

    private static final long serialVersionUID = -1954295220;

    /**
     * The reference instance of <code>stroom.STRM_TASK</code>
     */
    public static final StrmTask STRM_TASK = new StrmTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StrmTaskRecord> getRecordType() {
        return StrmTaskRecord.class;
    }

    /**
     * The column <code>stroom.STRM_TASK.ID</code>.
     */
    public final TableField<StrmTaskRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TASK.VER</code>.
     */
    public final TableField<StrmTaskRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TASK.CRT_MS</code>.
     */
    public final TableField<StrmTaskRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_TASK.END_TIME_MS</code>.
     */
    public final TableField<StrmTaskRecord, Long> END_TIME_MS = createField("END_TIME_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_TASK.STAT</code>.
     */
    public final TableField<StrmTaskRecord, Byte> STAT = createField("STAT", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TASK.STAT_MS</code>.
     */
    public final TableField<StrmTaskRecord, Long> STAT_MS = createField("STAT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_TASK.START_TIME_MS</code>.
     */
    public final TableField<StrmTaskRecord, Long> START_TIME_MS = createField("START_TIME_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_TASK.FK_ND_ID</code>.
     */
    public final TableField<StrmTaskRecord, Integer> FK_ND_ID = createField("FK_ND_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stroom.STRM_TASK.FK_STRM_ID</code>.
     */
    public final TableField<StrmTaskRecord, Long> FK_STRM_ID = createField("FK_STRM_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TASK.DAT</code>.
     */
    public final TableField<StrmTaskRecord, String> DAT = createField("DAT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.STRM_TASK.FK_STRM_PROC_FILT_ID</code>.
     */
    public final TableField<StrmTaskRecord, Integer> FK_STRM_PROC_FILT_ID = createField("FK_STRM_PROC_FILT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>stroom.STRM_TASK</code> table reference
     */
    public StrmTask() {
        this("STRM_TASK", null);
    }

    /**
     * Create an aliased <code>stroom.STRM_TASK</code> table reference
     */
    public StrmTask(String alias) {
        this(alias, STRM_TASK);
    }

    private StrmTask(String alias, Table<StrmTaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private StrmTask(String alias, Table<StrmTaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StrmTaskRecord, Long> getIdentity() {
        return Keys.IDENTITY_STRM_TASK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StrmTaskRecord> getPrimaryKey() {
        return Keys.KEY_STRM_TASK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StrmTaskRecord>> getKeys() {
        return Arrays.<UniqueKey<StrmTaskRecord>>asList(Keys.KEY_STRM_TASK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StrmTaskRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StrmTaskRecord, ?>>asList(Keys.STRM_TASK_FK_ND_ID, Keys.STRM_TASK_FK_STRM_PROC_FILT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTask as(String alias) {
        return new StrmTask(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StrmTask rename(String name) {
        return new StrmTask(name, null);
    }
}
