/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.StrmTpRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmTp extends TableImpl<StrmTpRecord> {

    private static final long serialVersionUID = -1006222082;

    /**
     * The reference instance of <code>stroom.STRM_TP</code>
     */
    public static final StrmTp STRM_TP = new StrmTp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StrmTpRecord> getRecordType() {
        return StrmTpRecord.class;
    }

    /**
     * The column <code>stroom.STRM_TP.ID</code>.
     */
    public final TableField<StrmTpRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TP.VER</code>.
     */
    public final TableField<StrmTpRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TP.CRT_USER</code>.
     */
    public final TableField<StrmTpRecord, String> CRT_USER = createField("CRT_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.STRM_TP.UPD_USER</code>.
     */
    public final TableField<StrmTpRecord, String> UPD_USER = createField("UPD_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.STRM_TP.NAME</code>.
     */
    public final TableField<StrmTpRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TP.EXT</code>.
     */
    public final TableField<StrmTpRecord, String> EXT = createField("EXT", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TP.PURP</code>.
     */
    public final TableField<StrmTpRecord, Byte> PURP = createField("PURP", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TP.PATH</code>.
     */
    public final TableField<StrmTpRecord, String> PATH = createField("PATH", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.STRM_TP.CRT_MS</code>.
     */
    public final TableField<StrmTpRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.STRM_TP.UPD_MS</code>.
     */
    public final TableField<StrmTpRecord, Long> UPD_MS = createField("UPD_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>stroom.STRM_TP</code> table reference
     */
    public StrmTp() {
        this("STRM_TP", null);
    }

    /**
     * Create an aliased <code>stroom.STRM_TP</code> table reference
     */
    public StrmTp(String alias) {
        this(alias, STRM_TP);
    }

    private StrmTp(String alias, Table<StrmTpRecord> aliased) {
        this(alias, aliased, null);
    }

    private StrmTp(String alias, Table<StrmTpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StrmTpRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STRM_TP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StrmTpRecord> getPrimaryKey() {
        return Keys.KEY_STRM_TP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StrmTpRecord>> getKeys() {
        return Arrays.<UniqueKey<StrmTpRecord>>asList(Keys.KEY_STRM_TP_PRIMARY, Keys.KEY_STRM_TP_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTp as(String alias) {
        return new StrmTp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StrmTp rename(String name) {
        return new StrmTp(name, null);
    }
}
