/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.VolStateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VolState extends TableImpl<VolStateRecord> {

    private static final long serialVersionUID = -478729812;

    /**
     * The reference instance of <code>stroom.VOL_STATE</code>
     */
    public static final VolState VOL_STATE = new VolState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VolStateRecord> getRecordType() {
        return VolStateRecord.class;
    }

    /**
     * The column <code>stroom.VOL_STATE.ID</code>.
     */
    public final TableField<VolStateRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.VOL_STATE.VER</code>.
     */
    public final TableField<VolStateRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.VOL_STATE.BYTES_USED</code>.
     */
    public final TableField<VolStateRecord, Long> BYTES_USED = createField("BYTES_USED", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.VOL_STATE.BYTES_FREE</code>.
     */
    public final TableField<VolStateRecord, Long> BYTES_FREE = createField("BYTES_FREE", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.VOL_STATE.BYTES_TOTL</code>.
     */
    public final TableField<VolStateRecord, Long> BYTES_TOTL = createField("BYTES_TOTL", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.VOL_STATE.STAT_MS</code>.
     */
    public final TableField<VolStateRecord, Long> STAT_MS = createField("STAT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>stroom.VOL_STATE</code> table reference
     */
    public VolState() {
        this("VOL_STATE", null);
    }

    /**
     * Create an aliased <code>stroom.VOL_STATE</code> table reference
     */
    public VolState(String alias) {
        this(alias, VOL_STATE);
    }

    private VolState(String alias, Table<VolStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private VolState(String alias, Table<VolStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VolStateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VOL_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VolStateRecord> getPrimaryKey() {
        return Keys.KEY_VOL_STATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VolStateRecord>> getKeys() {
        return Arrays.<UniqueKey<VolStateRecord>>asList(Keys.KEY_VOL_STATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VolState as(String alias) {
        return new VolState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VolState rename(String name) {
        return new VolState(name, null);
    }
}
