/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import stroom.models.Keys;
import stroom.models.Stroom;
import stroom.models.tables.records.XsltRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Xslt extends TableImpl<XsltRecord> {

    private static final long serialVersionUID = 1709126304;

    /**
     * The reference instance of <code>stroom.XSLT</code>
     */
    public static final Xslt XSLT = new Xslt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<XsltRecord> getRecordType() {
        return XsltRecord.class;
    }

    /**
     * The column <code>stroom.XSLT.ID</code>.
     */
    public final TableField<XsltRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.XSLT.VER</code>.
     */
    public final TableField<XsltRecord, Byte> VER = createField("VER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.XSLT.CRT_MS</code>.
     */
    public final TableField<XsltRecord, Long> CRT_MS = createField("CRT_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.XSLT.CRT_USER</code>.
     */
    public final TableField<XsltRecord, String> CRT_USER = createField("CRT_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.XSLT.UPD_MS</code>.
     */
    public final TableField<XsltRecord, Long> UPD_MS = createField("UPD_MS", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.XSLT.UPD_USER</code>.
     */
    public final TableField<XsltRecord, String> UPD_USER = createField("UPD_USER", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>stroom.XSLT.NAME</code>.
     */
    public final TableField<XsltRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.XSLT.UUID</code>.
     */
    public final TableField<XsltRecord, String> UUID = createField("UUID", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>stroom.XSLT.DESCRIP</code>.
     */
    public final TableField<XsltRecord, String> DESCRIP = createField("DESCRIP", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.XSLT.DAT</code>.
     */
    public final TableField<XsltRecord, String> DAT = createField("DAT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.XSLT.FK_FOLDER_ID</code>.
     */
    public final TableField<XsltRecord, Integer> FK_FOLDER_ID = createField("FK_FOLDER_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>stroom.XSLT</code> table reference
     */
    public Xslt() {
        this("XSLT", null);
    }

    /**
     * Create an aliased <code>stroom.XSLT</code> table reference
     */
    public Xslt(String alias) {
        this(alias, XSLT);
    }

    private Xslt(String alias, Table<XsltRecord> aliased) {
        this(alias, aliased, null);
    }

    private Xslt(String alias, Table<XsltRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<XsltRecord, Integer> getIdentity() {
        return Keys.IDENTITY_XSLT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<XsltRecord> getPrimaryKey() {
        return Keys.KEY_XSLT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<XsltRecord>> getKeys() {
        return Arrays.<UniqueKey<XsltRecord>>asList(Keys.KEY_XSLT_PRIMARY, Keys.KEY_XSLT_NAME, Keys.KEY_XSLT_UUID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<XsltRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<XsltRecord, ?>>asList(Keys.XSLT_FK_FOLDER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Xslt as(String alias) {
        return new Xslt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Xslt rename(String name) {
        return new Xslt(name, null);
    }
}
