/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.DocPerm;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocPermRecord extends UpdatableRecordImpl<DocPermRecord> implements Record6<Long, Byte, String, String, String, String> {

    private static final long serialVersionUID = -1107271274;

    /**
     * Setter for <code>stroom.DOC_PERM.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.DOC_PERM.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.DOC_PERM.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.DOC_PERM.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.DOC_PERM.USR_UUID</code>.
     */
    public void setUsrUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.DOC_PERM.USR_UUID</code>.
     */
    public String getUsrUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.DOC_PERM.DOC_TP</code>.
     */
    public void setDocTp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.DOC_PERM.DOC_TP</code>.
     */
    public String getDocTp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.DOC_PERM.DOC_UUID</code>.
     */
    public void setDocUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.DOC_PERM.DOC_UUID</code>.
     */
    public String getDocUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.DOC_PERM.PERM</code>.
     */
    public void setPerm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.DOC_PERM.PERM</code>.
     */
    public String getPerm() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Byte, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Byte, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DocPerm.DOC_PERM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return DocPerm.DOC_PERM.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DocPerm.DOC_PERM.USR_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DocPerm.DOC_PERM.DOC_TP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DocPerm.DOC_PERM.DOC_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DocPerm.DOC_PERM.PERM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsrUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDocTp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDocUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord value3(String value) {
        setUsrUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord value4(String value) {
        setDocTp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord value5(String value) {
        setDocUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord value6(String value) {
        setPerm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocPermRecord values(Long value1, Byte value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocPermRecord
     */
    public DocPermRecord() {
        super(DocPerm.DOC_PERM);
    }

    /**
     * Create a detached, initialised DocPermRecord
     */
    public DocPermRecord(Long id, Byte ver, String usrUuid, String docTp, String docUuid, String perm) {
        super(DocPerm.DOC_PERM);

        set(0, id);
        set(1, ver);
        set(2, usrUuid);
        set(3, docTp);
        set(4, docUuid);
        set(5, perm);
    }
}
