/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.StrmProc;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmProcRecord extends UpdatableRecordImpl<StrmProcRecord> implements Record9<Integer, Byte, String, String, String, Integer, Boolean, Long, Long> {

    private static final long serialVersionUID = 1434300023;

    /**
     * Setter for <code>stroom.STRM_PROC.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.CRT_USER</code>.
     */
    public void setCrtUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.CRT_USER</code>.
     */
    public String getCrtUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.UPD_USER</code>.
     */
    public void setUpdUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.UPD_USER</code>.
     */
    public String getUpdUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.TASK_TP</code>.
     */
    public void setTaskTp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.TASK_TP</code>.
     */
    public String getTaskTp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.FK_PIPE_ID</code>.
     */
    public void setFkPipeId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.FK_PIPE_ID</code>.
     */
    public Integer getFkPipeId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.ENBL</code>.
     */
    public void setEnbl(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.ENBL</code>.
     */
    public Boolean getEnbl() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.CRT_MS</code>.
     */
    public void setCrtMs(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.CRT_MS</code>.
     */
    public Long getCrtMs() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>stroom.STRM_PROC.UPD_MS</code>.
     */
    public void setUpdMs(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC.UPD_MS</code>.
     */
    public Long getUpdMs() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Byte, String, String, String, Integer, Boolean, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Byte, String, String, String, Integer, Boolean, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StrmProc.STRM_PROC.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return StrmProc.STRM_PROC.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StrmProc.STRM_PROC.CRT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StrmProc.STRM_PROC.UPD_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return StrmProc.STRM_PROC.TASK_TP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return StrmProc.STRM_PROC.FK_PIPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return StrmProc.STRM_PROC.ENBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return StrmProc.STRM_PROC.CRT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return StrmProc.STRM_PROC.UPD_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCrtUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUpdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTaskTp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFkPipeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getEnbl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCrtMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getUpdMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value3(String value) {
        setCrtUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value4(String value) {
        setUpdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value5(String value) {
        setTaskTp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value6(Integer value) {
        setFkPipeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value7(Boolean value) {
        setEnbl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value8(Long value) {
        setCrtMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord value9(Long value) {
        setUpdMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcRecord values(Integer value1, Byte value2, String value3, String value4, String value5, Integer value6, Boolean value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StrmProcRecord
     */
    public StrmProcRecord() {
        super(StrmProc.STRM_PROC);
    }

    /**
     * Create a detached, initialised StrmProcRecord
     */
    public StrmProcRecord(Integer id, Byte ver, String crtUser, String updUser, String taskTp, Integer fkPipeId, Boolean enbl, Long crtMs, Long updMs) {
        super(StrmProc.STRM_PROC);

        set(0, id);
        set(1, ver);
        set(2, crtUser);
        set(3, updUser);
        set(4, taskTp);
        set(5, fkPipeId);
        set(6, enbl);
        set(7, crtMs);
        set(8, updMs);
    }
}
