/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.StrmTask;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmTaskRecord extends UpdatableRecordImpl<StrmTaskRecord> implements Record11<Long, Byte, Long, Long, Byte, Long, Long, Integer, Long, String, Integer> {

    private static final long serialVersionUID = 595831615;

    /**
     * Setter for <code>stroom.STRM_TASK.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.CRT_MS</code>.
     */
    public void setCrtMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.CRT_MS</code>.
     */
    public Long getCrtMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.END_TIME_MS</code>.
     */
    public void setEndTimeMs(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.END_TIME_MS</code>.
     */
    public Long getEndTimeMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.STAT</code>.
     */
    public void setStat(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.STAT</code>.
     */
    public Byte getStat() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.STAT_MS</code>.
     */
    public void setStatMs(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.STAT_MS</code>.
     */
    public Long getStatMs() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.START_TIME_MS</code>.
     */
    public void setStartTimeMs(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.START_TIME_MS</code>.
     */
    public Long getStartTimeMs() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.FK_ND_ID</code>.
     */
    public void setFkNdId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.FK_ND_ID</code>.
     */
    public Integer getFkNdId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.FK_STRM_ID</code>.
     */
    public void setFkStrmId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.FK_STRM_ID</code>.
     */
    public Long getFkStrmId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.DAT</code>.
     */
    public void setDat(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.DAT</code>.
     */
    public String getDat() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stroom.STRM_TASK.FK_STRM_PROC_FILT_ID</code>.
     */
    public void setFkStrmProcFiltId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.STRM_TASK.FK_STRM_PROC_FILT_ID</code>.
     */
    public Integer getFkStrmProcFiltId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Byte, Long, Long, Byte, Long, Long, Integer, Long, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Byte, Long, Long, Byte, Long, Long, Integer, Long, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return StrmTask.STRM_TASK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return StrmTask.STRM_TASK.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return StrmTask.STRM_TASK.CRT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return StrmTask.STRM_TASK.END_TIME_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return StrmTask.STRM_TASK.STAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return StrmTask.STRM_TASK.STAT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return StrmTask.STRM_TASK.START_TIME_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return StrmTask.STRM_TASK.FK_ND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return StrmTask.STRM_TASK.FK_STRM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return StrmTask.STRM_TASK.DAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return StrmTask.STRM_TASK.FK_STRM_PROC_FILT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCrtMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEndTimeMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getStat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getStatMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getStartTimeMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getFkNdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getFkStrmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getFkStrmProcFiltId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value3(Long value) {
        setCrtMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value4(Long value) {
        setEndTimeMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value5(Byte value) {
        setStat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value6(Long value) {
        setStatMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value7(Long value) {
        setStartTimeMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value8(Integer value) {
        setFkNdId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value9(Long value) {
        setFkStrmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value10(String value) {
        setDat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord value11(Integer value) {
        setFkStrmProcFiltId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmTaskRecord values(Long value1, Byte value2, Long value3, Long value4, Byte value5, Long value6, Long value7, Integer value8, Long value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StrmTaskRecord
     */
    public StrmTaskRecord() {
        super(StrmTask.STRM_TASK);
    }

    /**
     * Create a detached, initialised StrmTaskRecord
     */
    public StrmTaskRecord(Long id, Byte ver, Long crtMs, Long endTimeMs, Byte stat, Long statMs, Long startTimeMs, Integer fkNdId, Long fkStrmId, String dat, Integer fkStrmProcFiltId) {
        super(StrmTask.STRM_TASK);

        set(0, id);
        set(1, ver);
        set(2, crtMs);
        set(3, endTimeMs);
        set(4, stat);
        set(5, statMs);
        set(6, startTimeMs);
        set(7, fkNdId);
        set(8, fkStrmId);
        set(9, dat);
        set(10, fkStrmProcFiltId);
    }
}
