/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.StrmProcFilt;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmProcFiltRecord extends UpdatableRecordImpl<StrmProcFiltRecord> implements Record11<Integer, Byte, Long, String, Long, String, String, Integer, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1774357357;

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.CRT_MS</code>.
     */
    public void setCrtMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.CRT_MS</code>.
     */
    public Long getCrtMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.CRT_USER</code>.
     */
    public void setCrtUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.CRT_USER</code>.
     */
    public String getCrtUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.UPD_MS</code>.
     */
    public void setUpdMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.UPD_MS</code>.
     */
    public Long getUpdMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.UPD_USER</code>.
     */
    public void setUpdUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.UPD_USER</code>.
     */
    public String getUpdUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.DAT</code>.
     */
    public void setDat(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.DAT</code>.
     */
    public String getDat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.PRIOR</code>.
     */
    public void setPrior(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.PRIOR</code>.
     */
    public Integer getPrior() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.FK_STRM_PROC_ID</code>.
     */
    public void setFkStrmProcId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.FK_STRM_PROC_ID</code>.
     */
    public Integer getFkStrmProcId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.FK_STRM_PROC_FILT_TRAC_ID</code>.
     */
    public void setFkStrmProcFiltTracId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.FK_STRM_PROC_FILT_TRAC_ID</code>.
     */
    public Integer getFkStrmProcFiltTracId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>stroom.STRM_PROC_FILT.ENBL</code>.
     */
    public void setEnbl(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.STRM_PROC_FILT.ENBL</code>.
     */
    public Boolean getEnbl() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Byte, Long, String, Long, String, String, Integer, Integer, Integer, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Byte, Long, String, Long, String, String, Integer, Integer, Integer, Boolean> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StrmProcFilt.STRM_PROC_FILT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return StrmProcFilt.STRM_PROC_FILT.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return StrmProcFilt.STRM_PROC_FILT.CRT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StrmProcFilt.STRM_PROC_FILT.CRT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return StrmProcFilt.STRM_PROC_FILT.UPD_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return StrmProcFilt.STRM_PROC_FILT.UPD_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return StrmProcFilt.STRM_PROC_FILT.DAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return StrmProcFilt.STRM_PROC_FILT.PRIOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return StrmProcFilt.STRM_PROC_FILT.FK_STRM_PROC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return StrmProcFilt.STRM_PROC_FILT.FK_STRM_PROC_FILT_TRAC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return StrmProcFilt.STRM_PROC_FILT.ENBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCrtMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrtUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUpdMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPrior();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getFkStrmProcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getFkStrmProcFiltTracId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getEnbl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value3(Long value) {
        setCrtMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value4(String value) {
        setCrtUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value5(Long value) {
        setUpdMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value6(String value) {
        setUpdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value7(String value) {
        setDat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value8(Integer value) {
        setPrior(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value9(Integer value) {
        setFkStrmProcId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value10(Integer value) {
        setFkStrmProcFiltTracId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord value11(Boolean value) {
        setEnbl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmProcFiltRecord values(Integer value1, Byte value2, Long value3, String value4, Long value5, String value6, String value7, Integer value8, Integer value9, Integer value10, Boolean value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StrmProcFiltRecord
     */
    public StrmProcFiltRecord() {
        super(StrmProcFilt.STRM_PROC_FILT);
    }

    /**
     * Create a detached, initialised StrmProcFiltRecord
     */
    public StrmProcFiltRecord(Integer id, Byte ver, Long crtMs, String crtUser, Long updMs, String updUser, String dat, Integer prior, Integer fkStrmProcId, Integer fkStrmProcFiltTracId, Boolean enbl) {
        super(StrmProcFilt.STRM_PROC_FILT);

        set(0, id);
        set(1, ver);
        set(2, crtMs);
        set(3, crtUser);
        set(4, updMs);
        set(5, updUser);
        set(6, dat);
        set(7, prior);
        set(8, fkStrmProcId);
        set(9, fkStrmProcFiltTracId);
        set(10, enbl);
    }
}
