/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.StrmVol;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrmVolRecord extends UpdatableRecordImpl<StrmVolRecord> implements Record4<Long, Byte, Long, Integer> {

    private static final long serialVersionUID = 1998600375;

    /**
     * Setter for <code>stroom.STRM_VOL.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.STRM_VOL.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.STRM_VOL.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.STRM_VOL.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.STRM_VOL.FK_STRM_ID</code>.
     */
    public void setFkStrmId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.STRM_VOL.FK_STRM_ID</code>.
     */
    public Long getFkStrmId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.STRM_VOL.FK_VOL_ID</code>.
     */
    public void setFkVolId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.STRM_VOL.FK_VOL_ID</code>.
     */
    public Integer getFkVolId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Byte, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Byte, Long, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return StrmVol.STRM_VOL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return StrmVol.STRM_VOL.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return StrmVol.STRM_VOL.FK_STRM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return StrmVol.STRM_VOL.FK_VOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getFkStrmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFkVolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmVolRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmVolRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmVolRecord value3(Long value) {
        setFkStrmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmVolRecord value4(Integer value) {
        setFkVolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StrmVolRecord values(Long value1, Byte value2, Long value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StrmVolRecord
     */
    public StrmVolRecord() {
        super(StrmVol.STRM_VOL);
    }

    /**
     * Create a detached, initialised StrmVolRecord
     */
    public StrmVolRecord(Long id, Byte ver, Long fkStrmId, Integer fkVolId) {
        super(StrmVol.STRM_VOL);

        set(0, id);
        set(1, ver);
        set(2, fkStrmId);
        set(3, fkVolId);
    }
}
