/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.StroomStatsStore;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StroomStatsStoreRecord extends UpdatableRecordImpl<StroomStatsStoreRecord> implements Record15<Integer, Byte, Long, String, Long, String, String, String, String, String, Boolean, Byte, Byte, String, Integer> {

    private static final long serialVersionUID = -1690811007;

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.CRT_MS</code>.
     */
    public void setCrtMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.CRT_MS</code>.
     */
    public Long getCrtMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.CRT_USER</code>.
     */
    public void setCrtUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.CRT_USER</code>.
     */
    public String getCrtUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.UPD_MS</code>.
     */
    public void setUpdMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.UPD_MS</code>.
     */
    public Long getUpdMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.UPD_USER</code>.
     */
    public void setUpdUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.UPD_USER</code>.
     */
    public String getUpdUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.NAME</code>.
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.NAME</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.UUID</code>.
     */
    public void setUuid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.UUID</code>.
     */
    public String getUuid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.DESCRIP</code>.
     */
    public void setDescrip(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.DESCRIP</code>.
     */
    public String getDescrip() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.PRES</code>.
     */
    public void setPres(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.PRES</code>.
     */
    public String getPres() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.ENBL</code>.
     */
    public void setEnbl(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.ENBL</code>.
     */
    public Boolean getEnbl() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.STAT_TP</code>.
     */
    public void setStatTp(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.STAT_TP</code>.
     */
    public Byte getStatTp() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.ROLLUP_TP</code>.
     */
    public void setRollupTp(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.ROLLUP_TP</code>.
     */
    public Byte getRollupTp() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.DAT</code>.
     */
    public void setDat(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.DAT</code>.
     */
    public String getDat() {
        return (String) get(13);
    }

    /**
     * Setter for <code>stroom.STROOM_STATS_STORE.FK_FOLDER_ID</code>.
     */
    public void setFkFolderId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>stroom.STROOM_STATS_STORE.FK_FOLDER_ID</code>.
     */
    public Integer getFkFolderId() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Byte, Long, String, Long, String, String, String, String, String, Boolean, Byte, Byte, String, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Byte, Long, String, Long, String, String, String, String, String, Boolean, Byte, Byte, String, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StroomStatsStore.STROOM_STATS_STORE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return StroomStatsStore.STROOM_STATS_STORE.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return StroomStatsStore.STROOM_STATS_STORE.CRT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StroomStatsStore.STROOM_STATS_STORE.CRT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return StroomStatsStore.STROOM_STATS_STORE.UPD_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return StroomStatsStore.STROOM_STATS_STORE.UPD_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return StroomStatsStore.STROOM_STATS_STORE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return StroomStatsStore.STROOM_STATS_STORE.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return StroomStatsStore.STROOM_STATS_STORE.DESCRIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return StroomStatsStore.STROOM_STATS_STORE.PRES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return StroomStatsStore.STROOM_STATS_STORE.ENBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return StroomStatsStore.STROOM_STATS_STORE.STAT_TP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return StroomStatsStore.STROOM_STATS_STORE.ROLLUP_TP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return StroomStatsStore.STROOM_STATS_STORE.DAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return StroomStatsStore.STROOM_STATS_STORE.FK_FOLDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCrtMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrtUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUpdMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDescrip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPres();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getEnbl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getStatTp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getRollupTp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getDat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getFkFolderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value3(Long value) {
        setCrtMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value4(String value) {
        setCrtUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value5(Long value) {
        setUpdMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value6(String value) {
        setUpdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value7(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value8(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value9(String value) {
        setDescrip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value10(String value) {
        setPres(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value11(Boolean value) {
        setEnbl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value12(Byte value) {
        setStatTp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value13(Byte value) {
        setRollupTp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value14(String value) {
        setDat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord value15(Integer value) {
        setFkFolderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StroomStatsStoreRecord values(Integer value1, Byte value2, Long value3, String value4, Long value5, String value6, String value7, String value8, String value9, String value10, Boolean value11, Byte value12, Byte value13, String value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StroomStatsStoreRecord
     */
    public StroomStatsStoreRecord() {
        super(StroomStatsStore.STROOM_STATS_STORE);
    }

    /**
     * Create a detached, initialised StroomStatsStoreRecord
     */
    public StroomStatsStoreRecord(Integer id, Byte ver, Long crtMs, String crtUser, Long updMs, String updUser, String name, String uuid, String descrip, String pres, Boolean enbl, Byte statTp, Byte rollupTp, String dat, Integer fkFolderId) {
        super(StroomStatsStore.STROOM_STATS_STORE);

        set(0, id);
        set(1, ver);
        set(2, crtMs);
        set(3, crtUser);
        set(4, updMs);
        set(5, updUser);
        set(6, name);
        set(7, uuid);
        set(8, descrip);
        set(9, pres);
        set(10, enbl);
        set(11, statTp);
        set(12, rollupTp);
        set(13, dat);
        set(14, fkFolderId);
    }
}
