/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.UsrGrpUsr;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsrGrpUsrRecord extends UpdatableRecordImpl<UsrGrpUsrRecord> implements Record4<Long, Byte, String, String> {

    private static final long serialVersionUID = -1525013091;

    /**
     * Setter for <code>stroom.USR_GRP_USR.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.USR_GRP_USR.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.USR_GRP_USR.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.USR_GRP_USR.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.USR_GRP_USR.GRP_UUID</code>.
     */
    public void setGrpUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.USR_GRP_USR.GRP_UUID</code>.
     */
    public String getGrpUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.USR_GRP_USR.USR_UUID</code>.
     */
    public void setUsrUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.USR_GRP_USR.USR_UUID</code>.
     */
    public String getUsrUuid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Byte, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Byte, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UsrGrpUsr.USR_GRP_USR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return UsrGrpUsr.USR_GRP_USR.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UsrGrpUsr.USR_GRP_USR.GRP_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UsrGrpUsr.USR_GRP_USR.USR_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGrpUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUsrUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrGrpUsrRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrGrpUsrRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrGrpUsrRecord value3(String value) {
        setGrpUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrGrpUsrRecord value4(String value) {
        setUsrUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrGrpUsrRecord values(Long value1, Byte value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsrGrpUsrRecord
     */
    public UsrGrpUsrRecord() {
        super(UsrGrpUsr.USR_GRP_USR);
    }

    /**
     * Create a detached, initialised UsrGrpUsrRecord
     */
    public UsrGrpUsrRecord(Long id, Byte ver, String grpUuid, String usrUuid) {
        super(UsrGrpUsr.USR_GRP_USR);

        set(0, id);
        set(1, ver);
        set(2, grpUuid);
        set(3, usrUuid);
    }
}
