/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.Usr;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsrRecord extends UpdatableRecordImpl<UsrRecord> implements Record17<Integer, Byte, Long, String, Long, String, String, String, Boolean, Byte, Short, Boolean, Long, Long, Long, String, Short> {

    private static final long serialVersionUID = 536508747;

    /**
     * Setter for <code>stroom.USR.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.USR.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.USR.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.USR.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.USR.CRT_MS</code>.
     */
    public void setCrtMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.USR.CRT_MS</code>.
     */
    public Long getCrtMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.USR.CRT_USER</code>.
     */
    public void setCrtUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.USR.CRT_USER</code>.
     */
    public String getCrtUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.USR.UPD_MS</code>.
     */
    public void setUpdMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.USR.UPD_MS</code>.
     */
    public Long getUpdMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.USR.UPD_USER</code>.
     */
    public void setUpdUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.USR.UPD_USER</code>.
     */
    public String getUpdUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.USR.NAME</code>.
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.USR.NAME</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.USR.UUID</code>.
     */
    public void setUuid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.USR.UUID</code>.
     */
    public String getUuid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.USR.GRP</code>.
     */
    public void setGrp(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.USR.GRP</code>.
     */
    public Boolean getGrp() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>stroom.USR.STAT</code>.
     */
    public void setStat(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.USR.STAT</code>.
     */
    public Byte getStat() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>stroom.USR.CUR_LOGIN_FAIL</code>.
     */
    public void setCurLoginFail(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.USR.CUR_LOGIN_FAIL</code>.
     */
    public Short getCurLoginFail() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>stroom.USR.LOGIN_EXPIRY</code>.
     */
    public void setLoginExpiry(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.USR.LOGIN_EXPIRY</code>.
     */
    public Boolean getLoginExpiry() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>stroom.USR.LAST_LOGIN_MS</code>.
     */
    public void setLastLoginMs(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.USR.LAST_LOGIN_MS</code>.
     */
    public Long getLastLoginMs() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>stroom.USR.LOGIN_VALID_MS</code>.
     */
    public void setLoginValidMs(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>stroom.USR.LOGIN_VALID_MS</code>.
     */
    public Long getLoginValidMs() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>stroom.USR.PASS_EXPIRY_MS</code>.
     */
    public void setPassExpiryMs(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>stroom.USR.PASS_EXPIRY_MS</code>.
     */
    public Long getPassExpiryMs() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>stroom.USR.PASS_HASH</code>.
     */
    public void setPassHash(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>stroom.USR.PASS_HASH</code>.
     */
    public String getPassHash() {
        return (String) get(15);
    }

    /**
     * Setter for <code>stroom.USR.TOTL_LOGIN_FAIL</code>.
     */
    public void setTotlLoginFail(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>stroom.USR.TOTL_LOGIN_FAIL</code>.
     */
    public Short getTotlLoginFail() {
        return (Short) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, Byte, Long, String, Long, String, String, String, Boolean, Byte, Short, Boolean, Long, Long, Long, String, Short> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, Byte, Long, String, Long, String, String, String, Boolean, Byte, Short, Boolean, Long, Long, Long, String, Short> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usr.USR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Usr.USR.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Usr.USR.CRT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Usr.USR.CRT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Usr.USR.UPD_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Usr.USR.UPD_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Usr.USR.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Usr.USR.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Usr.USR.GRP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Usr.USR.STAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field11() {
        return Usr.USR.CUR_LOGIN_FAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return Usr.USR.LOGIN_EXPIRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Usr.USR.LAST_LOGIN_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Usr.USR.LOGIN_VALID_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Usr.USR.PASS_EXPIRY_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Usr.USR.PASS_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field17() {
        return Usr.USR.TOTL_LOGIN_FAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCrtMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrtUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUpdMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getGrp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getStat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value11() {
        return getCurLoginFail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getLoginExpiry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getLastLoginMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getLoginValidMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getPassExpiryMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getPassHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value17() {
        return getTotlLoginFail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value3(Long value) {
        setCrtMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value4(String value) {
        setCrtUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value5(Long value) {
        setUpdMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value6(String value) {
        setUpdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value7(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value8(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value9(Boolean value) {
        setGrp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value10(Byte value) {
        setStat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value11(Short value) {
        setCurLoginFail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value12(Boolean value) {
        setLoginExpiry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value13(Long value) {
        setLastLoginMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value14(Long value) {
        setLoginValidMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value15(Long value) {
        setPassExpiryMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value16(String value) {
        setPassHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord value17(Short value) {
        setTotlLoginFail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsrRecord values(Integer value1, Byte value2, Long value3, String value4, Long value5, String value6, String value7, String value8, Boolean value9, Byte value10, Short value11, Boolean value12, Long value13, Long value14, Long value15, String value16, Short value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsrRecord
     */
    public UsrRecord() {
        super(Usr.USR);
    }

    /**
     * Create a detached, initialised UsrRecord
     */
    public UsrRecord(Integer id, Byte ver, Long crtMs, String crtUser, Long updMs, String updUser, String name, String uuid, Boolean grp, Byte stat, Short curLoginFail, Boolean loginExpiry, Long lastLoginMs, Long loginValidMs, Long passExpiryMs, String passHash, Short totlLoginFail) {
        super(Usr.USR);

        set(0, id);
        set(1, ver);
        set(2, crtMs);
        set(3, crtUser);
        set(4, updMs);
        set(5, updUser);
        set(6, name);
        set(7, uuid);
        set(8, grp);
        set(9, stat);
        set(10, curLoginFail);
        set(11, loginExpiry);
        set(12, lastLoginMs);
        set(13, loginValidMs);
        set(14, passExpiryMs);
        set(15, passHash);
        set(16, totlLoginFail);
    }
}
