/*
 * Copyright 2017 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * This file is generated by jOOQ.
*/
package stroom.models.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.models.tables.Vis;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VisRecord extends UpdatableRecordImpl<VisRecord> implements Record13<Integer, Byte, Long, String, Long, String, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = -1830677861;

    /**
     * Setter for <code>stroom.VIS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.VIS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.VIS.VER</code>.
     */
    public void setVer(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.VIS.VER</code>.
     */
    public Byte getVer() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.VIS.CRT_MS</code>.
     */
    public void setCrtMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.VIS.CRT_MS</code>.
     */
    public Long getCrtMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.VIS.CRT_USER</code>.
     */
    public void setCrtUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.VIS.CRT_USER</code>.
     */
    public String getCrtUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.VIS.UPD_MS</code>.
     */
    public void setUpdMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.VIS.UPD_MS</code>.
     */
    public Long getUpdMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.VIS.UPD_USER</code>.
     */
    public void setUpdUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.VIS.UPD_USER</code>.
     */
    public String getUpdUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.VIS.NAME</code>.
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.VIS.NAME</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.VIS.UUID</code>.
     */
    public void setUuid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.VIS.UUID</code>.
     */
    public String getUuid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.VIS.DESCRIP</code>.
     */
    public void setDescrip(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.VIS.DESCRIP</code>.
     */
    public String getDescrip() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.VIS.FUNC_NAME</code>.
     */
    public void setFuncName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.VIS.FUNC_NAME</code>.
     */
    public String getFuncName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stroom.VIS.SCRIPT</code>.
     */
    public void setScript(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.VIS.SCRIPT</code>.
     */
    public String getScript() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stroom.VIS.SETTINGS</code>.
     */
    public void setSettings(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.VIS.SETTINGS</code>.
     */
    public String getSettings() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stroom.VIS.FK_FOLDER_ID</code>.
     */
    public void setFkFolderId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.VIS.FK_FOLDER_ID</code>.
     */
    public Integer getFkFolderId() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Byte, Long, String, Long, String, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Byte, Long, String, Long, String, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vis.VIS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Vis.VIS.VER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Vis.VIS.CRT_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Vis.VIS.CRT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Vis.VIS.UPD_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Vis.VIS.UPD_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Vis.VIS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Vis.VIS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Vis.VIS.DESCRIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Vis.VIS.FUNC_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Vis.VIS.SCRIPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Vis.VIS.SETTINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Vis.VIS.FK_FOLDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCrtMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrtUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUpdMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDescrip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getFuncName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getScript();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSettings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getFkFolderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value2(Byte value) {
        setVer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value3(Long value) {
        setCrtMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value4(String value) {
        setCrtUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value5(Long value) {
        setUpdMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value6(String value) {
        setUpdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value7(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value8(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value9(String value) {
        setDescrip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value10(String value) {
        setFuncName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value11(String value) {
        setScript(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value12(String value) {
        setSettings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord value13(Integer value) {
        setFkFolderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VisRecord values(Integer value1, Byte value2, Long value3, String value4, Long value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VisRecord
     */
    public VisRecord() {
        super(Vis.VIS);
    }

    /**
     * Create a detached, initialised VisRecord
     */
    public VisRecord(Integer id, Byte ver, Long crtMs, String crtUser, Long updMs, String updUser, String name, String uuid, String descrip, String funcName, String script, String settings, Integer fkFolderId) {
        super(Vis.VIS);

        set(0, id);
        set(1, ver);
        set(2, crtMs);
        set(3, crtUser);
        set(4, updMs);
        set(5, updUser);
        set(6, name);
        set(7, uuid);
        set(8, descrip);
        set(9, funcName);
        set(10, script);
        set(11, settings);
        set(12, fkFolderId);
    }
}
